### PR TITLE
Optimization / Performance cleanup

### LINKED ISSUE #207: Analyze Closure Compiler Output to help Improve Wasm Output
Since we now have Closure Compiler builds, noticed that closure can do huge performance improvements for our JS Builds. Got some advice that we can configure closure to not mangle names. And we can check and see what functions are being inlined, that may improve performance binaryen may not already be doing for us 😄

### LINKED ISSUE #221: i8Portable is not handle all cases and overcomplicated
I suggest replace `i8Portable` implementation which currently looks like this:
```js
function checkBitOnByte(bitPosition, byte) {
  return (byte & (1 << bitPosition)) != 0;
}

function i8Portable(param) {
  // JS ints are all i32, therefore, get the sign bit, and then convert accordingly
  // Example: https://blog.michaelyin.info/convert-8bit-byte-to-signed-int/
  let response = param;
  if (checkBitOnByte(7, response)) {
    response = (256 - param) * -1;
  }

  return response;
}
```
And not handle this case for example:
```js
i8Portable(260) // return 260 but should 4
```

To this:
```js
function i8Portable(param) {
  return param << 24 >> 24;
}
```

### LINKED ISSUE #230: Suggest optimizion for retrive image buffer.
Current method: https://github.com/torch2424/wasmBoy/blob/bcc26f197b9516f136d385b7ffad1d7734b7d4da/lib/graphics/worker/imageData.js#L4

could be optimize to:
```ts
import { GAMEBOY_CAMERA_WIDTH, GAMEBOY_CAMERA_HEIGHT } from '../constants';
// move out creation of buffers, which is not cheap
const imageDataArray = new Uint8ClampedArray(GAMEBOY_CAMERA_HEIGHT * GAMEBOY_CAMERA_WIDTH * 4);

// use non-closure version for method
export function getImageDataFromGraphicsFrameBuffer(wasmByteMemory) {
   for (let y = 0; y < GAMEBOY_CAMERA_HEIGHT; ++y) {
    let stride1 = y * (GAMEBOY_CAMERA_WIDTH * 3);
    let stride2 = y * (GAMEBOY_CAMERA_WIDTH * 4);
    for (let x = 0; x < GAMEBOY_CAMERA_WIDTH; ++x) {
      const pixelStart = stride1 + x * 3;
      const imageDataIndex = stride2 + (x << 2);
      imageDataArray[imageDataIndex + 0] = wasmByteMemory[pixelStart + 0];
      imageDataArray[imageDataIndex + 1] = wasmByteMemory[pixelStart + 1];
      imageDataArray[imageDataIndex + 2] = wasmByteMemory[pixelStart + 2];
      // Alpha, no transparency
      imageDataArray[imageDataIndex + 3] = 255;
    }
  }
  return imageDataArray;
}

```

### PR DESCRIPTION
**Pull request by torch2424**
closes #230 
closes #221
relates to #216 
closes #207 

This does some general optimizations across the app. And some general performance things mentioned that should be done. Also, this finally removes the legacy API from forever ago, and cleans that up.

In terms of performance, I've noticed this being between 1.02 - 1.04 times as fast than the current master. Which is nice, but it may just be a placebo type thing.

# Screenshots

Everything working, and some benchmarks

screen shot 2019-02-21 at 1 53 51 am
screen shot 2019-02-21 at 2 05 33 am
screen shot 2019-02-21 at 2 05 45 am

### CODE REVIEW

**Comment by torch2424** [comment]
cc @MaxGraey 😄 Implemented your issues.

Though if you check the travis, seems like something on the latest master doesn't like the `@inline` decorator? 🤔

**Comment by MaxGraey** [comment]
cc @dcodeIO 
```
@inline export const enum CharCode {
 ~~~~~~~
 in ~lib/internal/string.ts(112,0)
ERROR: Parse error
    at parseBacklog (/home/travis/build/torch2424/wasmboy/node_modules/assemblyscript/cli/asc.js:363:23)
    at Object.main (/home/travis/build/torch2424/wasmboy/node_modules/assemblyscript/cli/asc.js:390:16)
    at Object.<anonymous> (/home/travis/build/torch2424/wasmboy/node_modules/assemblyscript/bin/asc:3:60)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
```

**Comment by dcodeIO** [comment]
I just recently made a change [here](https://github.com/AssemblyScript/assemblyscript/commit/34d86a0d6a24a0155dc3b4d8a5400a41d1aab0fe#diff-6518fffc4e430fcc63cd30eb07131a95L214) that addressed a similar issue. Might that have borked it? Or is the AS version used here older?

**Comment by MaxGraey** [comment]
@torch2424 your local build works without this error? Try clean travis cache

**Comment by dcodeIO** [comment]
Also keep in mind that dist files haven't been updated yet

**Comment by torch2424** [comment]
@MaxGraey My local build did work, but then I:

* `rm -rf node_modules && rm package-lock.json`
* `npm install`

And then I was getting the same error. However, I can try `travis clean cache` once I get home tonight.

@dcodeIO 

Are the dist files used for the `asc` compiler? Perhaps I need to build from source, or wait until those are updated?

**Comment by torch2424** [comment]
@MaxGraey Actually, it seems like I don't have a travis cache. Thus, I can't clear it 😢

**Comment by torch2424** [comment]
Oh I guess it fixed itself, through another master update 😄

**Pull request merged**
