### PR TITLE
Postfixes

### PR DESCRIPTION
**Pull request by MaxGraey**
Okey. I fixed most of portable issues. ~~But it seems some of one still exists. So wasm and closure versions works, but `pure js` it seems have some glitches~~ All works at last!

### CODE REVIEW

**Comment by MaxGraey** [comment]
Ok. All fixed !!!

**Comment by MaxGraey** [comment]
Ready to merge

**Comment by MaxGraey** [comment]
btw may be better rename `core.untouched.wasm` rename to `core.optimized.wasm`? =)

**Comment by torch2424** [comment]
@MaxGraey Yay! Thank you! 😄 

Also, opened an issue for your suggestion: #269

I can do that no worries 👍

**Pull request merged**
